--liquibase formatted sql
--changeset george:dml_05

INSERT INTO celebrity (name)
VALUES
    ('Zoe Saldana'),
    ('Sam Worthington'),
    ('Michelle Yeoh'),
    ('Dwayne Johnson'),
    ('Aldis Hodge'),
    ('Pierce Brosnan'),
    ('Will Smith'),
    ('Ben Foster'),
    ('Steven Ogg'),
    ('Eddie Redmayne'),
    ('Jude Law'),
    ('Ezra Miller'),
    ('Amber Midthunder'),
    ('Dakota Beavers'),
    ('Dane DiLiegro'),
    ('James Marsden'),
    ('Jim Carrey'),
    ('Ben Schwartz'),
    ('Robert Pattinson'),
    ('Zoë Kravitz'),
    ('Jeffrey Wright'),
    ('Keanu Reeves'),
    ('Carrie-Anne Moss'),
    ('Yahya Abdul-Mateen II'),
    ('Chris Hemsworth'),
    ('Natalie Portman'),
    ('Christian Bale'),
    ('Tom Cruise'),
    ('Jennifer Connelly'),
    ('Miles Teller');